[package]
name = "lib-notify"
version = "0.1.0"
edition = "2021"
description = "Library to send notify"

[dependencies]
chrono = "0.4.38"
gethostname = "0.5.0"
queues = "1.1.0"
reqwest = "0.12.5"
rustelebot = "0.3.2"
serde = "1.0.204"
serde_json = "1.0.120"
